using System.Data.Common;
using EasyReasy.Database;
using EasyReasy.EnvironmentVariables;

namespace EasyReasy.Metrics.IntegrationTests
{
    /// <summary>
    /// Defines the xUnit test collection so all test classes share a single fixture instance.
    /// </summary>
    [CollectionDefinition("Database")]
    public class DatabaseCollection : ICollectionFixture<TestDatabaseFixture>
    {
    }

    /// <summary>
    /// Provides a shared PostgreSQL data source for all metrics integration tests.
    /// Creates the metric_snapshot table on initialization, drops it on teardown.
    /// Used as a collection fixture so it is created once per test run.
    /// </summary>
    public class TestDatabaseFixture : IAsyncLifetime
    {
        private DbDataSource _dataSource = null!;
        private IDbSessionFactory _sessionFactory = null!;

        /// <summary>
        /// Gets the database data source for creating connections.
        /// </summary>
        public DbDataSource DataSource => _dataSource;

        /// <summary>
        /// Gets the session factory for creating database sessions.
        /// </summary>
        public IDbSessionFactory SessionFactory => _sessionFactory;

        /// <inheritdoc />
        public async Task InitializeAsync()
        {
            string variablesFilePath = Path.Combine("..", "..", "EnvironmentVariables.txt");

            if (!File.Exists(variablesFilePath))
            {
                string exampleContent = EnvironmentVariableHelper.GetExampleContent(
                    "DATABASE_CONNECTION_STRING", "Host=localhost;Port=5432;Database=easy-reasy-metrics-test;Username=postgres;Password=postgres");

                File.WriteAllText(variablesFilePath, exampleContent);
            }

            EnvironmentVariableHelper.LoadVariablesFromFile(variablesFilePath);
            EnvironmentVariableHelper.ValidateVariableNamesIn(typeof(EnvironmentVariables));

            string connectionString = EnvironmentVariables.DatabaseConnectionString.GetValue();

            NpgsqlDataSourceFactory factory = new NpgsqlDataSourceFactory();
            _dataSource = factory.CreateDataSource(connectionString);
            _sessionFactory = new DbSessionFactory(_dataSource);

            await using (DbConnection connection = await _dataSource.OpenConnectionAsync())
            await using (DbCommand command = connection.CreateCommand())
            {
                command.CommandText = @"
                    CREATE TABLE IF NOT EXISTS metric_snapshot (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        metric_key TEXT NOT NULL,
                        collected_at TIMESTAMPTZ NOT NULL,
                        value NUMERIC NOT NULL
                    );

                    CREATE INDEX IF NOT EXISTS idx_metric_snapshot_key_collected
                        ON metric_snapshot (metric_key, collected_at DESC);

                    DELETE FROM metric_snapshot;";
                await command.ExecuteNonQueryAsync();
            }
        }

        /// <inheritdoc />
        public async Task DisposeAsync()
        {
            await using DbConnection connection = await _dataSource.OpenConnectionAsync();
            await using DbCommand command = connection.CreateCommand();
            command.CommandText = @"DROP TABLE IF EXISTS metric_snapshot;";
            await command.ExecuteNonQueryAsync();

            if (_dataSource is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }
    }
}
